server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

spring:
  datasource:
    url: ${STI_DB_URL:jdbc:postgresql://localhost:5432/space_tours_inc}
    username: ${STI_DB_USERNAME:stiuser}
    password: ${STI_DB_PASSWORD:stipass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate.ddl-auto: none
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc.time_zone: UTC
      temp.use_jdbc_metadata_defaults: false

# Actuator
management:
  endpoints:
    web:
      base-path: /api/mgmt
      exposure:
        include: flyway, health, info, metrics, prometheus

# API documentation / Swagger
springdoc:
  swagger-ui:
    display-request-duration: true
    operationsSorter: method
    disable-swagger-default-url: true
  show-actuator: true

# External services
propellant:
  baseUri: ${STI_PROPELLANT_BASEURI:https://us-central1-propellant-markt-inc-api.cloudfunctions.net}
  client:
    connectTimeout: 3000
    readTimeout: 3000
